### ISSUE TITLE
CK Editor Links cannot be added in Course Description

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#101]
![bildschirmfoto 2017-09-24 um 09 15 33](https://user-images.githubusercontent.com/26879902/30780373-6991e072-a109-11e7-909b-fe3866cffc3a.png)

**Comment by roggnroll** [comment]
Probably this might be solved with solving #80

**Comment by roggnroll** [comment]
Photos are also not available. 
The same problem can be observed in the ckeditor that allows to change the "user about" section for displaying board member information texts. 
Looks like all of our own plugins are affected. The normal CMS on the homepage is working.

**Comment by renatobellotti** [comment]
I'll see if I can fix this without performing the Big Update, i. e. solving #80.

I won't touch any dependency without having unit tests for at least the payment and course apps. If we mess up something there, we destroy our financial foundation. Quästur'll kill us^^

**Comment by roggnroll** [comment]
I don't if it's worth the effort. Probably better to solve #80 and then see if it persists. Maybe let's also wait a week or two because now ppl need our system most urgently.

**Comment by roggnroll** [comment]
I can still add links and pics by directly editing the code - but you can't expect that from the average user

**Comment by renatobellotti** [comment]
Should be fixed. Please test it.

The solution was to run the following commands on the server:
```shell
docker-compose run --rm django python3 manage.py cms check
docker-compose run --rm django python3 manage.py cms delete-orphaned-plugins
```
You have to confirm the last command manually.

**Comment by renatobellotti** [comment]
This is still not fixed.

**Comment by TobiMarg** [comment]
Links can now be added with the new "Link" button in the editor toolbar, but the CMS Plugins are still not shown...

**Comment by TobiMarg** [comment]
As this is not a CMS page I think the best option would be not to display that dropdown at all. This is implemented in bcb50e4.
